//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Releases struct {
	ID            string `sql:"primary_key"`
	InputID       string `sql:"primary_key"`
	InputProvider string `sql:"primary_key"`
	Provider      string `sql:"primary_key"`
	ReleasedAt    string
	Raw           []byte
}
