//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Releases struct {
	ID                 string `sql:"primary_key"`
	InternalProviderID string
	InputID            string
	Title              string
	Description        *string
	ImageURL           *string
	ExternalLink       *string
	ReleasedAt         string
}
