FROM amacneil/dbmate:2.34.1

WORKDIR /app

COPY ./internal/storage/migrations ./migrations

RUN mkdir /app/data

VOLUME [ "/app/data" ]

ENTRYPOINT [ ]
CMD [ "dbmate", "-u", "sqlite:./data/app.db", "-d", "./migrations", "--no-dump-schema", "up" ]
