FROM amacneil/dbmate:2.29.5

WORKDIR /app

COPY ./src/common/database/migrations ./migrations

RUN mkdir /app/data

VOLUME [ "/app/data" ]

ENTRYPOINT [ ]
CMD [ "dbmate", "-u", "sqlite:./data/app.db", "-d", "./migrations", "--no-dump-schema", "up" ]
