[settings]
lockfile = true

[env]
CGO_ENABLED = 0

[tools]
dbmate = "2.33.0"
ginkgo = "2.29.0"
"github:a-h/templ" = "0.3.1020"
go = "1.26.4"
"go:github.com/go-jet/jet/v2/cmd/jet" = "2.15.0"
"go:github.com/mickamy/slog-pretty/cmd/spretty" = "0.0.1"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.3.0"
golangci-lint = "2.12.2"
sqlite = "3.53.1"

[tasks."code:test"]
run = "ginkgo -r -p --randomize-all --randomize-suites --fail-on-pending --fail-on-empty --keep-going --trace"

[tasks."code:check"]
run = [
  "golangci-lint run ./...",
  "golangci-lint fmt --diff-colored ./...",
  "govulncheck -test ./...",
]

[tasks."cmd:admin-server"]
run = [
  "rm -rfv internal/entrypoints/apps/admin_server/.dist",
  "go run -ldflags \"-w -s\" cmd/bundle_assets/main.go -e internal/entrypoints/apps/admin_server/frontend/*.css,internal/entrypoints/apps/admin_server/frontend/*.ts -o internal/entrypoints/apps/admin_server/.dist",
  "cp --verbose -R internal/entrypoints/apps/admin_server/frontend/static internal/entrypoints/apps/admin_server/.dist",
  "touch internal/entrypoints/apps/admin_server/.dist/.gitkeep",
  "templ generate",
  "go run -ldflags \"-w -s\" cmd/main/main.go app admin-server",
]

[tasks."cmd:db-migrate"]
run = [
  "dbmate -u 'sqlite:./data/app.db' -d ./internal/storage/migrations -s ./internal/storage/schema.sql up",
  "go run -ldflags \"-w -s\" cmd/gen_db_types/main.go",
]

[tasks."cmd:fetch-releases"]
run = ["go run -ldflags \"-w -s\" cmd/main/main.go job fetch-releases"]
