//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Outputs = newOutputsTable("", "outputs", "")

type outputsTable struct {
	sqlite.Table

	// Columns
	ID            sqlite.ColumnString
	InputID       sqlite.ColumnString
	InputProvider sqlite.ColumnString
	Provider      sqlite.ColumnString
	Raw           sqlite.ColumnBlob

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type OutputsTable struct {
	outputsTable

	EXCLUDED outputsTable
}

// AS creates new OutputsTable with assigned alias
func (a OutputsTable) AS(alias string) *OutputsTable {
	return newOutputsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OutputsTable with assigned schema name
func (a OutputsTable) FromSchema(schemaName string) *OutputsTable {
	return newOutputsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OutputsTable with assigned table prefix
func (a OutputsTable) WithPrefix(prefix string) *OutputsTable {
	return newOutputsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OutputsTable with assigned table suffix
func (a OutputsTable) WithSuffix(suffix string) *OutputsTable {
	return newOutputsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOutputsTable(schemaName, tableName, alias string) *OutputsTable {
	return &OutputsTable{
		outputsTable: newOutputsTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newOutputsTableImpl("", "excluded", ""),
	}
}

func newOutputsTableImpl(schemaName, tableName, alias string) outputsTable {
	var (
		IDColumn            = sqlite.StringColumn("id")
		InputIDColumn       = sqlite.StringColumn("input_id")
		InputProviderColumn = sqlite.StringColumn("input_provider")
		ProviderColumn      = sqlite.StringColumn("provider")
		RawColumn           = sqlite.BlobColumn("raw")
		allColumns          = sqlite.ColumnList{IDColumn, InputIDColumn, InputProviderColumn, ProviderColumn, RawColumn}
		mutableColumns      = sqlite.ColumnList{RawColumn}
		defaultColumns      = sqlite.ColumnList{InputIDColumn, InputProviderColumn}
	)

	return outputsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		InputID:       InputIDColumn,
		InputProvider: InputProviderColumn,
		Provider:      ProviderColumn,
		Raw:           RawColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
