//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Releases = newReleasesTable("", "releases", "")

type releasesTable struct {
	sqlite.Table

	// Columns
	ID            sqlite.ColumnString
	InputID       sqlite.ColumnString
	InputProvider sqlite.ColumnString
	Provider      sqlite.ColumnString
	ReleasedAt    sqlite.ColumnString
	Raw           sqlite.ColumnBlob

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ReleasesTable struct {
	releasesTable

	EXCLUDED releasesTable
}

// AS creates new ReleasesTable with assigned alias
func (a ReleasesTable) AS(alias string) *ReleasesTable {
	return newReleasesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ReleasesTable with assigned schema name
func (a ReleasesTable) FromSchema(schemaName string) *ReleasesTable {
	return newReleasesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ReleasesTable with assigned table prefix
func (a ReleasesTable) WithPrefix(prefix string) *ReleasesTable {
	return newReleasesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ReleasesTable with assigned table suffix
func (a ReleasesTable) WithSuffix(suffix string) *ReleasesTable {
	return newReleasesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newReleasesTable(schemaName, tableName, alias string) *ReleasesTable {
	return &ReleasesTable{
		releasesTable: newReleasesTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newReleasesTableImpl("", "excluded", ""),
	}
}

func newReleasesTableImpl(schemaName, tableName, alias string) releasesTable {
	var (
		IDColumn            = sqlite.StringColumn("id")
		InputIDColumn       = sqlite.StringColumn("input_id")
		InputProviderColumn = sqlite.StringColumn("input_provider")
		ProviderColumn      = sqlite.StringColumn("provider")
		ReleasedAtColumn    = sqlite.StringColumn("released_at")
		RawColumn           = sqlite.BlobColumn("raw")
		allColumns          = sqlite.ColumnList{IDColumn, InputIDColumn, InputProviderColumn, ProviderColumn, ReleasedAtColumn, RawColumn}
		mutableColumns      = sqlite.ColumnList{ReleasedAtColumn, RawColumn}
		defaultColumns      = sqlite.ColumnList{InputIDColumn, InputProviderColumn}
	)

	return releasesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		InputID:       InputIDColumn,
		InputProvider: InputProviderColumn,
		Provider:      ProviderColumn,
		ReleasedAt:    ReleasedAtColumn,
		Raw:           RawColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
