//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Releases = newReleasesTable("", "releases", "")

type releasesTable struct {
	sqlite.Table

	// Columns
	ID                 sqlite.ColumnString
	InternalProviderID sqlite.ColumnString
	InputID            sqlite.ColumnString
	Title              sqlite.ColumnString
	Description        sqlite.ColumnString
	ImageURL           sqlite.ColumnString
	ExternalLink       sqlite.ColumnString
	ReleasedAt         sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ReleasesTable struct {
	releasesTable

	EXCLUDED releasesTable
}

// AS creates new ReleasesTable with assigned alias
func (a ReleasesTable) AS(alias string) *ReleasesTable {
	return newReleasesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ReleasesTable with assigned schema name
func (a ReleasesTable) FromSchema(schemaName string) *ReleasesTable {
	return newReleasesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ReleasesTable with assigned table prefix
func (a ReleasesTable) WithPrefix(prefix string) *ReleasesTable {
	return newReleasesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ReleasesTable with assigned table suffix
func (a ReleasesTable) WithSuffix(suffix string) *ReleasesTable {
	return newReleasesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newReleasesTable(schemaName, tableName, alias string) *ReleasesTable {
	return &ReleasesTable{
		releasesTable: newReleasesTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newReleasesTableImpl("", "excluded", ""),
	}
}

func newReleasesTableImpl(schemaName, tableName, alias string) releasesTable {
	var (
		IDColumn                 = sqlite.StringColumn("id")
		InternalProviderIDColumn = sqlite.StringColumn("internal_provider_id")
		InputIDColumn            = sqlite.StringColumn("input_id")
		TitleColumn              = sqlite.StringColumn("title")
		DescriptionColumn        = sqlite.StringColumn("description")
		ImageURLColumn           = sqlite.StringColumn("image_url")
		ExternalLinkColumn       = sqlite.StringColumn("external_link")
		ReleasedAtColumn         = sqlite.StringColumn("released_at")
		allColumns               = sqlite.ColumnList{IDColumn, InternalProviderIDColumn, InputIDColumn, TitleColumn, DescriptionColumn, ImageURLColumn, ExternalLinkColumn, ReleasedAtColumn}
		mutableColumns           = sqlite.ColumnList{InternalProviderIDColumn, InputIDColumn, TitleColumn, DescriptionColumn, ImageURLColumn, ExternalLinkColumn, ReleasedAtColumn}
		defaultColumns           = sqlite.ColumnList{InputIDColumn}
	)

	return releasesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		InternalProviderID: InternalProviderIDColumn,
		InputID:            InputIDColumn,
		Title:              TitleColumn,
		Description:        DescriptionColumn,
		ImageURL:           ImageURLColumn,
		ExternalLink:       ExternalLinkColumn,
		ReleasedAt:         ReleasedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
