//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Inputs = newInputsTable("", "inputs", "")

type inputsTable struct {
	sqlite.Table

	// Columns
	ID       sqlite.ColumnString
	Provider sqlite.ColumnString
	Raw      sqlite.ColumnBlob

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type InputsTable struct {
	inputsTable

	EXCLUDED inputsTable
}

// AS creates new InputsTable with assigned alias
func (a InputsTable) AS(alias string) *InputsTable {
	return newInputsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new InputsTable with assigned schema name
func (a InputsTable) FromSchema(schemaName string) *InputsTable {
	return newInputsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new InputsTable with assigned table prefix
func (a InputsTable) WithPrefix(prefix string) *InputsTable {
	return newInputsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new InputsTable with assigned table suffix
func (a InputsTable) WithSuffix(suffix string) *InputsTable {
	return newInputsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newInputsTable(schemaName, tableName, alias string) *InputsTable {
	return &InputsTable{
		inputsTable: newInputsTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newInputsTableImpl("", "excluded", ""),
	}
}

func newInputsTableImpl(schemaName, tableName, alias string) inputsTable {
	var (
		IDColumn       = sqlite.StringColumn("id")
		ProviderColumn = sqlite.StringColumn("provider")
		RawColumn      = sqlite.BlobColumn("raw")
		allColumns     = sqlite.ColumnList{IDColumn, ProviderColumn, RawColumn}
		mutableColumns = sqlite.ColumnList{RawColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return inputsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:       IDColumn,
		Provider: ProviderColumn,
		Raw:      RawColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
