#!/usr/bin/env sh

set -e

# =====================================
# GLOBALS
# =====================================

SCRIPT_DIR="$(cd "$(dirname -- "$0")" >/dev/null 2>&1 && pwd -P)"
SCRIPT_PATH="$SCRIPT_DIR/$(basename -- "$0")"
PS4='\033[35m$\033[0m '

# =====================================
# UTILS
# =====================================

__utils__print_and_exec() {
  printf "\033[35m$\033[0m %s\n" "$*"
  "$@"
  return $?
}

__utils__list_tasks() {
  while IFS= read -r line; do
    case "$line" in
      task__*)
        final="${line#"task__"}"
        final="${final%"() {"}"
        printf "%s\n" "$final"
      ;;
    esac
  done < "$SCRIPT_PATH"
}

__utils__task_in_tasks() {
  for task_in_tasks__task in $2; do
    if [ "$task_in_tasks__task" = "$1" ]; then
      return 0
    fi
  done

  return 1
}

# =====================================
# TASKS
# =====================================

__cmd_compile() {
  compile__cmd_name="$1"

  __utils__print_and_exec rm --verbose -f ".bin/$compile__cmd_name"
  __utils__print_and_exec go build -ldflags "-w -s" -o ".bin/$compile__cmd_name" "cmd/$compile__cmd_name/main.go"
}

task__code_test() {
  task__cmd_db_migrate
  __task__cmd_admin_server_assets

  __utils__print_and_exec ginkgo \
    -r \
    -p \
    --randomize-all \
    --randomize-suites \
    --fail-on-pending \
    --fail-on-empty \
    --keep-going \
    --trace
}

task__code_check() {
  task__cmd_db_migrate
  __task__cmd_admin_server_assets

  __utils__print_and_exec golangci-lint run ./...
  __utils__print_and_exec golangci-lint fmt --diff-colored ./...
}

task__deps_update() {
  __utils__print_and_exec go get -u ./...
  __utils__print_and_exec go mod tidy
}

__task__cmd_admin_server_assets() {
  __utils__print_and_exec rm -rfv cmd/admin_server/.dist
  __utils__print_and_exec go run scripts/bundle_assets/main.go \
    -e cmd/admin_server/frontend/*.css \
    -e cmd/admin_server/frontend/*.ts \
    -o cmd/admin_server/.dist
  __utils__print_and_exec cp --verbose -R cmd/admin_server/frontend/static cmd/admin_server/.dist
  __utils__print_and_exec templ generate
}

task__cmd_admin_server() {
  __task__cmd_admin_server_assets
  __cmd_compile "admin_server"
  __utils__print_and_exec .bin/admin_server "$@" | spretty
}

task__cmd_db_migrate() {
  __cmd_compile "db_migrate"
  __utils__print_and_exec .bin/db_migrate "$@" | spretty

  __utils__print_and_exec go run scripts/gen_db_types/main.go
  set -x; sqlite3 data/app.db ".schema" > internal/store/schema.sql; { set +x; } 2>/dev/null
}

task__cmd_fetch_outputs() {
  __cmd_compile "fetch_outputs_job"
  __utils__print_and_exec .bin/fetch_outputs_job "$@" | spretty
}

main() {
  tasks="$(__utils__list_tasks)"
  task="$1"

  if ! __utils__task_in_tasks "$task" "$tasks"; then
    printf "Task \"%s\" not available\n\n" "$task"
    printf "Possible tasks:\n%s\n" "$tasks"
    exit 1
  fi

  shift

  __utils__print_and_exec task__"$task" "$@"
}

main "$@"
